### ISSUE TITLE
经常下载到一半会卡住

### ISSUE THREAD

**Issue by zjp-shadow** [libthu/reserves-lib-tsinghua-downloader#3]
大概如下图，我重复多次都卡了。
每次卡顿的位置还不太一样，是经常性的事件，设置 interval 无改善。
最后将 concurrent 设置为 1 成功下载。
![image](https://user-images.githubusercontent.com/46623500/221871652-bcffdd07-31f4-47d5-8fd0-34111b8d93e4.png)

**Comment by liblaf** [comment]
我也遇到了类似的情况, 但我是将 `concurrent` 设置为一个很大的值, 比如 `64`, 然后挂在后台 (`tmux`) 去做别的事. 我遇到的卡顿并不是卡死, 只是卡顿的时间很长, 甚至长达几分钟. 好在它不会中断, 所以如果时间充裕放着等也问题不大.

另外, `interval` 的注释有些歧义, 从源码 [utils.py/claw.py#L71](https://github.com/libthu/reserves-lib-tsinghua-downloader/blob/fc572989216c9197127decb327e6e302db55a0b9/utils/claw.py#L71) 来看并不是相邻请求的间隔时间, 而是 **爬取两个章节之间的间隔**. 大部分教材每一章都不短, 还有些教材在教参平台上没有分章, 这时 `interval` 的作用就约等于没有. 我猜可以试一试在每一页爬取完成后, 也就是 [utils/concurrent.py](https://github.com/libthu/reserves-lib-tsinghua-downloader/blob/main/utils/concurrent.py) 加一小段延迟, 尽管大幅改善的可能性不大.

**Comment by i207M** [comment]
@zjp-shadow 我自己尝试了一下，是可以正常下载的。但是你的情况我也可以理解，毕竟ban IP这种事，玄学。

@liblaf 谢谢分享经验。我怀疑是`session.get`在失败的时候会重试几次。

**Comment by i207M** [comment]
> 另外, `interval` 的注释有些歧义, 从源码 [utils.py/claw.py#L71](https://github.com/libthu/reserves-lib-tsinghua-downloader/blob/fc572989216c9197127decb327e6e302db55a0b9/utils/claw.py#L71) 来看并不是相邻请求的间隔时间, 而是 **爬取两个章节之间的间隔**. 大部分教材每一章都不短, 还有些教材在教参平台上没有分章, 这时 `interval` 的作用就约等于没有. 我猜可以试一试在每一页爬取完成后, 也就是 [utils/concurrent.py](https://github.com/libthu/reserves-lib-tsinghua-downloader/blob/main/utils/concurrent.py) 加一小段延迟, 尽管大幅改善的可能性不大.

有道理，需要修改

**Comment by libthu** [comment]
@liblaf @i207M 已将修改推送至dev分支。
@liblaf 在宿舍和教学楼的网络下，程序运行的速度不一样。开发者在六教测试时，有的请求需要30s才能返回。需要进一步研究。

**Comment by libthu** [comment]
Close as no further reports
