### ISSUE TITLE
MacOS打开downloader时显示“未能打开文稿“downloader”。文本编码中文(GB 18030)不适用。”

### ISSUE THREAD

**Issue by ElayneC** [libthu/reserves-lib-tsinghua-downloader#7]

**Comment by libthu** [comment]
请确认一下后缀名。这不是一个文本文件。也许试一下这个：

因为它没有“执行权限”。

解决方法：在终端中进入 downloader 文件所在的文件夹，执行 chmod +x downloader 命令。有关此命令的更多帮助请参阅 [Apple](https://support.apple.com/zh-cn/guide/terminal/apdd100908f-06b3-4e63-8a87-32e71241bab4/mac)。

**Comment by ElayneC** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    您好。该文件的简介如图，我不知道它原本应该是什么后缀名。按【因为它没有“执行权限”】下的解决方法处理后，仍未能安装。
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                940071021
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
 
    

  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年09月18日 11:08
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [libthu/reserves-lib-tsinghua-downloader] MacOS打开downloader时显示“未能打开文稿“downloader”。文本编码中文(GB 18030)不适用。” (Issue #7)
        
      
    
  
  
请确认一下后缀名。这不是一个文本文件。也许试一下这个：
因为它没有“执行权限”。
解决方法：在终端中进入 downloader 文件所在的文件夹，执行 chmod +x downloader 命令。有关此命令的更多帮助请参阅 Apple。

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by libthu** [comment]
尝试一下在终端里运行解压后的downloader？类似于`./downloader`

**Comment by libthu** [comment]
Closing the issue as of no reply
